### ISSUE TITLE
Edit on Github link is broken on autoapi generated .NET docs

### ISSUE THREAD

**Issue by agjohnson** [rtfd/sphinx-autoapi#31]
We are linking to our generated url, not the url provided by `docfx`:

```yaml
source:
  remote: *o0
  path: src/Microsoft.AspNet.Identity/IUserClaimStore.cs
  startLine: 33
```

They might also be broken on other languages.
