### ISSUE TITLE
Handling generic types

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#58]
Generic types in the docfx metadata format are identified using a [spec identifier](http://dotnet.github.io/docfx/spec/metadata_dotnet_spec.html#2-2-spec-identifiers) format that represents generic type parameters with curly brackets. This format is for referencing purposes in the metadata documents, but it is showing up in the rendered docs (ex see the user argument and the return value of the [GetSecurityStampAsync](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNet/Identity/EntityFramework/UserStore-TUser-TRole-TContext-TKey/index.html?highlight=getsecuritystampasync#Microsoft.AspNet.Identity.EntityFramework.UserStore<TUser, TRole, TContext, TKey>.GetSecurityStampAsync) method:

![image](https://cloud.githubusercontent.com/assets/1874516/12775475/4de0914a-ca03-11e5-9fcf-477c7dd75888.png)

![image](https://cloud.githubusercontent.com/assets/1874516/12775471/412f48f6-ca03-11e5-9f76-4845849686ae.png)

Instead these "spec identifiers" should be resolved to their user friendly names for display purposes. I believe this data is available for lookup in the references section of the generated metadata documents:

```yaml
- uid: System.Threading.Tasks.Task{System.String}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<String>
  name.vb: Task(Of String)
  fullName: System.Threading.Tasks.Task<System.String>
  fullName.vb: System.Threading.Tasks.Task(Of System.String)
```
